# Generated by Django 6.1.1 on 2026-10-05 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(help_text='فقط حروف انگلیسی، عدد و خط تیره. در نشانی صفحه استفاده می\u200cشود.', max_length=200, unique=True, verbose_name='نامک')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(verbose_name='توضیح کامل')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('cover', models.ImageField(blank=True, upload_to='covers/', verbose_name='تصویر جلد')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('delivery_email_body', models.TextField(help_text='بعد از خرید برای خریدار ایمیل می\u200cشود: لینک، رمز و راهنمای دسترسی.', verbose_name='متن ایمیل تحویل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=120, verbose_name='نام خریدار')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='ایمیل خریدار')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت\u200cشده'), ('failed', 'ناموفق')], default='pending', max_length=16, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='courses.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
